services:
  mysql:
    ports:
      - "3306:3306"
    image: 'mysql:latest'
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_DATABASE: forum
      TZ: Asia/Tokyo