USE forum;

DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
	user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	nickname VARCHAR(32) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	authority VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS temporary_users(
	user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	nickname VARCHAR(32) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	authentication_code VARCHAR(255) NOT NULL
);